Repository RocketChat/EmbeddedChat, pull requests merged in 2025-01, with the labels that each got.

#845 fix : Add Hover Effect to FileMessage Component
  packages/react/src/views/FileMessage/FileMessage.js
Labels: testing

#922 Fix: attachment and avatar size in messages
  packages/react/src/views/AttachmentHandler/AudioAttachment.js
  packages/react/src/views/AttachmentHandler/VideoAttachment.js
  packages/react/src/views/Message/Message.styles.js
  packages/react/src/views/Message/MessageAvatarContainer.js
Labels: testing

#810 feat: implement loading of older messages functionality
  packages/api/src/EmbeddedChatApi.ts
  packages/react/src/hooks/useFetchChatData.js
  packages/react/src/store/messageStore.js
  packages/react/src/views/ChatBody/ChatBody.js
  packages/react/src/views/ChatBody/ChatBody.styles.js
  packages/react/src/views/Message/Message.js
  packages/react/src/views/MessageList/MessageList.js
Labels: epic, testing

#926 feat : added icon to show Update ChannelHeader and RoomInfo UI for (Channels Converted to Teams).
  packages/react/src/store/channelStore.js
  packages/react/src/views/ChatHeader/ChatHeader.js
  packages/react/src/views/RoomInformation/RoomInformation.js
  packages/ui-elements/src/components/Icon/icons/Team.js
  packages/ui-elements/src/components/Icon/icons/index.js
  packages/ui-elements/tools/icons-generator.js
Labels: chore

#930 chore: Feat + Fix: added searchbar + emoji name and fixed emoji picker position
  packages/react/src/views/EmojiPicker/EmojiPicker.js
  packages/react/src/views/EmojiPicker/EmojiPicker.styles.js
Labels: chore, testing

#693 fix: ChatInput Formatter Tool UI for small screens
  packages/react/src/views/ChatInput/AudioMessageRecorder.js
  packages/react/src/views/ChatInput/ChatInput.js
  packages/react/src/views/ChatInput/ChatInput.styles.js
  packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js
  packages/react/src/views/ChatInput/VideoMessageRecoder.js
  packages/react/src/views/QuoteMessage/QuoteMessage.styles.js
Labels: testing
