Repository RocketChat/EmbeddedChat, pull requests merged in 2025-02, with the labels that each got.

#917 fix: upgrade actions/upload-artifact to v4 to address deprecation
  .github/workflows/playwright.yml
Labels: discussion

#940 fix: Code Block Overflow and Add Backdrop for Announcement Modal
  packages/markups/src/elements/CodeBlock.js
  packages/react/src/views/ChatBody/ChatBody.js
Labels: chore, testing

#786 Feat: Enhanced 'Email' and 'Created At' Fields of User Info
  packages/react/src/lib/formatTimestampGetDate.js
  packages/react/src/views/UserInformation/UserInformation.js
Labels: testing

#802 Feat: Add keyboard shortcuts for closing modal (Escape) and submitting (Enter) in File Upload Window
  packages/react/src/views/AttachmentPreview/AttachmentPreview.js
Labels: chore, testing

#820 chore/feat: Add tooltip displaying users who reacted with a particular emoji
  packages/react/src/views/EmojiReaction/EmojiReaction.js
  packages/react/src/views/Message/Message.styles.js
  packages/react/src/views/Message/MessageReactions.js
Labels: chore, testing

#829 feat: Add file size in attached docs and Tooltips for downloads/collapse/title options.
  packages/react/src/views/AttachmentHandler/AttachmentMetadata.js
  packages/react/src/views/AttachmentHandler/AudioAttachment.js
  packages/react/src/views/AttachmentHandler/ImageAttachment.js
  packages/react/src/views/AttachmentHandler/VideoAttachment.js
Labels: question, testing

#807 feat: Add keyboard shortcut key for moving starting and ending of the message
  packages/react/src/views/ChatInput/ChatInput.js
Labels: chore, testing

#921 fix: Added avatar in thread message
  packages/react/src/views/ChatHeader/ChatHeader.js
  packages/react/src/views/DynamicHeader/DynamicHeader.js
  packages/react/src/views/DynamicHeader/DynamicHeader.styles.js
  packages/react/src/views/Message/Message.styles.js
  packages/react/src/views/Message/MessageMetrics.js
Labels: chore, nudge
