Repository RocketChat/EmbeddedChat, pull requests merged in 2025-05, with the labels that each got.

#767 fix: correct delete messages permission behavior in Administration and resolve permissions index issue
  packages/api/src/EmbeddedChatApi.ts
  packages/react/src/hooks/useFetchChatData.js
  packages/react/src/hooks/useRCAuth.js
  packages/react/src/store/messageStore.js
  packages/react/src/views/ChatBody/ChatBody.js
  packages/react/src/views/EmbeddedChat.js
  packages/react/src/views/Message/Message.js
  packages/react/src/views/Message/MessageToolbox.js
Labels: testing

#836 fix: resolve mention highlighting issue for "application" and "text" file types and improve design
  packages/react/src/views/AttachmentHandler/Attachment.js
  packages/react/src/views/AttachmentHandler/AttachmentMetadata.js
  packages/react/src/views/AttachmentHandler/TextAttachment.js
  packages/react/src/views/Message/BubbleVariant/Bubble.styles.js
  packages/react/src/views/MessageAggregators/MentionedMessages.js
  packages/react/src/views/QuoteMessage/QuoteMessage.js
  packages/ui-elements/src/components/Button/Button.styles.js
Labels: testing

#905 fix: correct UI for archived channels and display channel topic
  packages/api/src/EmbeddedChatApi.ts
  packages/react/src/store/channelStore.js
  packages/react/src/views/ChatHeader/ChatHeader.js
  packages/react/src/views/ChatHeader/ChatHeader.styles.js
  packages/react/src/views/ChatInput/ChatInput.js
  packages/react/src/views/RoomInformation/RoomInformation.js
  packages/react/src/views/RoomInformation/RoomInformation.styles.js
Labels: testing

#990 feat: Added Support for displaying the timestamp messages
  packages/markups/src/elements/InlineElements.js
  packages/markups/src/elements/TimestampElement.js
Labels: enhancement, testing

#991 Fix: Alt + Arrow Key Shortcuts Not Functioning in Message Navigation
  packages/react/src/views/ChatInput/ChatInput.js
Labels: chore, testing

#912 Added color to the link messages & link present in link preview based on light and dark theme
  packages/markups/src/elements/LinkSpan.js
  packages/react/src/views/LinkPreview/LinkPreview.js
Labels: chore, testing

#889 feat: Add a Preview Feature to check the text after formatting it.
  package.json
  packages/react/src/store/messageStore.js
  packages/react/src/views/ChatInput/ChatInput.js
  packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js
  packages/react/src/views/PreviewMessage/PreviewMessage.js
  packages/react/src/views/PreviewMessage/PreviewMessage.styles.js
  yarn.lock
Labels: discussion
